# Use Node.js LTS image
FROM node:18

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .

# Expose the app port
EXPOSE 80

# Start the app
CMD ["node", "index.js"]
