services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5001:5001"

  ride-service:
    build: ./services/ride
    container_name: ride-service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq

  notification-service:
    build: ./services/notification
    container_name: notification-service
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - ride-service
      - payment-service
      - notification-service

  # ---------- UI SERVICES ----------

  ui-users:
    image: nginx:alpine
    container_name: ui-users
    volumes:
      - ./ui/users:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - api-gateway

  ui-ride:
    image: nginx:alpine
    container_name: ui-ride
    volumes:
      - ./ui/ride:/usr/share/nginx/html
    ports:
      - "8082:80"
    depends_on:
      - api-gateway

  ui-driver:
    image: nginx:alpine
    container_name: ui-driver
    volumes:
      - ./ui/driver:/usr/share/nginx/html
    ports:
      - "8083:80"
    depends_on:
      - api-gateway

  ui-payment:
    image: nginx:alpine
    container_name: ui-payment
    volumes:
      - ./ui/payment:/usr/share/nginx/html
    ports:
      - "8084:80"
    depends_on:
      - api-gateway

  ui-notification:
    image: nginx:alpine
    container_name: ui-notification
    volumes:
      - ./ui/notification:/usr/share/nginx/html
    ports:
      - "8085:80"
    depends_on:
      - api-gateway
