services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5001:5001"

  ride-service:
    build: ./services/ride
    container_name: ride-service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq

  notification-service:
    build: ./services/notification
    container_name: notification-service
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - ride-service
      - payment-service
      - notification-service
