apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672             # Used by backend services to connect
      targetPort: 5672
      nodePort: 30672        # Optional, or leave blank to auto-assign
    - name: management
      port: 15672            # RabbitMQ UI dashboard
      targetPort: 15672
      nodePort: 31672        # Access UI via localhost:31672
