apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      containers:
        - name: ride-service
          image: cab-booking-system-ride-service:latest
          ports:
            - containerPort: 5002
